### ISSUE TITLE
non atomic migrations

### ISSUE THREAD

**Issue by r3m0t** [Pankrat/pankrat.github.io#4]
https://docs.djangoproject.com/en/1.11/howto/writing-migrations/#non-atomic-migrations

> On databases that support DDL transactions (SQLite and PostgreSQL), migrations will run inside a transaction by default. For use cases such as performing data migrations on large tables, you may want to prevent a migration from running in a transaction by setting the atomic attribute to False:

**Comment by Pankrat** [comment]
Thanks for the pointer. I've updated the article.
